name: mice_heroes_01
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # route and toast current versions
  auto_route: ^0.6.9
  fluttertoast: ^7.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.9+3
  build_runner:


flutter:

  uses-material-design: true

# import everyting in assets folder (make directory first)
  assets:
    - assets/


  # config file created but app doesnt really have anything yet, and dependencies we need to bring in route and toast
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf







